"""
Jarvis Skill: Code Generation

Enables Jarvis to generate new agent files, skill modules, and test files.
All generated code goes through validation before being written to disk.
"""

from __future__ import annotations

import os
import textwrap
from datetime import datetime, timezone
from typing import Optional

import structlog

logger = structlog.get_logger(component="jarvis.code_generation")

SRC_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))


class CodeGenerator:
    """Generates Python code for new agents, skills, and tests."""

    def __init__(self, src_root: str = SRC_ROOT):
        self.src_root = src_root

    def generate_agent_file(
        self,
        role: str,
        agent_name: str,
        identity_core: str,
        agent_type: str = "SPECIALIST",
        methods: Optional[list[dict]] = None,
    ) -> str:
        """
        Generate a complete agent .py file.

        Args:
            role: AgentRole enum value (e.g., "CTO")
            agent_name: Human-readable name (e.g., "CTO Agent")
            identity_core: The immutable identity prompt
            agent_type: EXECUTIVE, MANAGER, ANALYST, or SPECIALIST
            methods: List of method definitions [{"name": ..., "docstring": ..., "body": ...}]

        Returns:
            The file path of the generated agent file.
        """
        safe_role = role.lower()
        filename = f"{safe_role}_agent.py"
        filepath = os.path.join(self.src_root, "agents", filename)

        methods_code = ""
        if methods:
            for m in methods:
                methods_code += f'''
    async def {m["name"]}(self, **kwargs) -> dict:
        """{m.get("docstring", "")}"""
        {m.get("body", "pass")}
'''

        code = textwrap.dedent(f'''
"""
{agent_name}

Auto-generated by Jarvis on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


{role.upper()}_IDENTITY_CORE = """{identity_core}"""


class {role.title().replace("_", "")}Agent(BaseAgent):
    """
    {agent_name} — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="{agent_name}",
            agent_role=AgentRole.{role.upper()},
            agent_type=AgentType.{agent_type.upper()},
            identity_core={role.upper()}_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)
{methods_code}
    def _safe_default(self, error: str) -> dict[str, Any]:
        return {{
            "content": f"{agent_name} encountered an error: {{error}}",
            "status": "error",
            "error": error,
        }}
''').lstrip()

        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w") as f:
            f.write(code)

        logger.info("agent_file_generated", role=role, path=filepath)
        return filepath

    def generate_skill_file(
        self,
        agent_role: str,
        skill_name: str,
        description: str,
        class_name: Optional[str] = None,
        methods: Optional[list[dict]] = None,
    ) -> str:
        """
        Generate a skill module for an agent.

        Args:
            agent_role: The agent's role directory name (e.g., "jarvis")
            skill_name: The skill file name without .py (e.g., "data_analyzer")
            description: What this skill does
            class_name: The class name (auto-derived if not provided)
            methods: List of method defs

        Returns:
            The file path of the generated skill file.
        """
        if not class_name:
            class_name = "".join(w.title() for w in skill_name.split("_"))

        filepath = os.path.join(
            self.src_root, "agents", "skills", agent_role.lower(), f"{skill_name}.py"
        )

        methods_code = ""
        if methods:
            for m in methods:
                params = m.get("params", "self")
                methods_code += f'''
    def {m["name"]}({params}):
        """{m.get("docstring", "")}"""
        {m.get("body", "pass")}
'''

        code = textwrap.dedent(f'''
"""
{description}

Auto-generated by Jarvis on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
"""

from __future__ import annotations

import structlog

logger = structlog.get_logger(component="{agent_role}.{skill_name}")


class {class_name}:
    """{description}"""
{methods_code if methods_code else "    pass"}
''').lstrip()

        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w") as f:
            f.write(code)

        logger.info("skill_file_generated", agent=agent_role, skill=skill_name, path=filepath)
        return filepath

    def generate_test_file(
        self,
        target_module: str,
        test_cases: Optional[list[dict]] = None,
    ) -> str:
        """
        Generate a test file for a target module.

        Args:
            target_module: The module to test (e.g., "agents.cto_agent")
            test_cases: Optional list of test case definitions

        Returns:
            The file path of the generated test file.
        """
        module_name = target_module.split(".")[-1]
        filepath = os.path.join(
            self.src_root, "tests", "unit", f"test_{module_name}.py"
        )

        tests_code = ""
        if test_cases:
            for tc in test_cases:
                tests_code += f'''
def test_{tc["name"]}():
    """{tc.get("docstring", "")}"""
    {tc.get("body", "pass")}
'''
        else:
            tests_code = f'''
def test_{module_name}_import():
    """Verify the module can be imported."""
    import {target_module}
    assert {target_module} is not None
'''

        code = textwrap.dedent(f'''
"""
Tests for {target_module}

Auto-generated by Jarvis on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
"""

import pytest
{tests_code}
''').lstrip()

        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w") as f:
            f.write(code)

        logger.info("test_file_generated", module=target_module, path=filepath)
        return filepath

    def generate_goals_md(
        self,
        agent_role: str,
        agent_name: str,
        mission: str,
        kpis: list[str],
        skills: list[str],
        evolution_targets: list[str],
        constraints: list[str],
    ) -> str:
        """Generate a goals.md file for an agent."""
        filepath = os.path.join(
            self.src_root, "agents", "skills", agent_role.lower(), "goals.md"
        )

        kpi_lines = "\n".join(f"- {kpi}" for kpi in kpis)
        skill_lines = "\n".join(f"- {s}" for s in skills)
        target_lines = "\n".join(f"- [ ] {t}" for t in evolution_targets)
        constraint_lines = "\n".join(f"- {c}" for c in constraints)

        content = textwrap.dedent(f"""
# {agent_name} — Goals & Mission

## Mission
{mission}

## Key Performance Indicators
{kpi_lines}

## Current Skills
{skill_lines}

## Evolution Targets
{target_lines}

## Constraints
{constraint_lines}
""").lstrip()

        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w") as f:
            f.write(content)

        logger.info("goals_generated", agent=agent_role, path=filepath)
        return filepath
