"""
PR Review Pipeline

Orchestrates the full review flow:
  1. Run pre-submit checks (syntax, security, tests)
  2. If pre-submit passes → create PR
  3. Run AI code review on the PR
  4. Post review as a GitHub comment
  5. Auto-approve safe PRs, request changes for risky ones

Called by bug_worker AFTER code is generated, BEFORE PR is submitted.
Also runs as a background loop to review any unreviewed PRs.
"""

from __future__ import annotations

import os
import asyncio
from datetime import datetime, timezone
from typing import Optional

import structlog

logger = structlog.get_logger(component="pr_review_pipeline")

SRC_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


class PRReviewPipeline:
    """Full PR review pipeline: presubmit → PR → AI review → post."""

    def __init__(self):
        self._review_count = 0
        self._history: list[dict] = []
        # In-memory dedup: PR numbers we've already reviewed this process lifecycle
        self._reviewed_prs: set[int] = set()

    async def presubmit_and_create_pr(
        self,
        bug: dict,
        files_created: list[str],
        github_ops,
    ) -> Optional[dict]:
        """
        Run pre-submit checks, then create PR if they pass.
        Called by bug_worker instead of directly creating a PR.

        Returns:
            PR info dict with review results, or None on failure.
        """
        from agents.skills.pr_reviewer.presubmit import run_presubmit

        abs_files = [
            f if os.path.isabs(f) else os.path.join(SRC_ROOT, f)
            for f in files_created
        ]

        # ── Step 1: Pre-submit checks ─────────────────────────────
        logger.info("presubmit_starting", files=len(abs_files), bug=bug.get("title", "")[:40])
        report = run_presubmit(abs_files, repo_root=os.path.dirname(SRC_ROOT))

        presubmit_md = report.to_markdown()

        if not report.passed:
            logger.warning(
                "presubmit_failed",
                errors=report.error_count,
                checks=[c.name for c in report.checks if not c.passed],
            )

            # Notify via Telegram
            try:
                from integrations.telegram_bot import send_alert
                failed_checks = ", ".join(c.name for c in report.checks if not c.passed)
                await send_alert(
                    f"⚠️ *Pre-Submit Failed*\n\n"
                    f"Bug: `{bug.get('title', '?')[:50]}`\n"
                    f"Failed: {failed_checks}\n"
                    f"Errors: {report.error_count}\n\n"
                    f"PR will NOT be created until issues are fixed."
                )
            except Exception:
                pass

            return {
                "pr": None,
                "presubmit": report.to_dict(),
                "review": None,
                "blocked": True,
                "reason": f"Pre-submit failed: {report.error_count} errors",
            }

        logger.info("presubmit_passed", files=report.total_files, warnings=report.warning_count)

        # ── Step 2: Create branch + PR ────────────────────────────
        bug_id = bug["id"][:8]
        bug_title = bug.get("title", "fix")[:40]
        safe_title = "".join(
            c if c.isalnum() or c in "-_" else "-"
            for c in bug_title.lower()
        ).strip("-")
        timestamp = datetime.now().strftime("%m%d-%H%M")
        branch = f"fix/{safe_title}-{timestamp}"

        files_list = "\n".join(f"- `{f}`" for f in files_created)

        pr_body = (
            f"## Bug Fix: {bug.get('title', '?')}\n\n"
            f"**Source:** {bug.get('source', 'manual')}\n"
            f"**Severity:** {bug.get('severity', '?')}\n"
            f"**Bug ID:** `{bug_id}`\n\n"
            f"### Files Changed\n{files_list}\n\n"
            f"{presubmit_md}\n\n"
            f"---\n"
            f"_Automatically generated by Jarvis Bug Worker_"
        )

        pr_result = await github_ops.evolution_commit_and_pr(
            branch_name=branch,
            files=abs_files,
            commit_message=f"[BugWorker] {bug.get('severity', 'FIX')}: {bug.get('title', 'fix')[:60]}",
            pr_title=f"[{bug.get('severity', 'FIX')}] {bug.get('title', 'Bug fix')[:70]}",
            pr_body=pr_body,
        )

        if not pr_result or not pr_result.get("number"):
            return {
                "pr": pr_result,
                "presubmit": report.to_dict(),
                "review": None,
                "blocked": False,
                "reason": "PR creation failed (branch pushed but API PR failed)",
            }

        pr_number = pr_result["number"]
        logger.info("pr_created", number=pr_number, url=pr_result.get("url"))

        # ── Step 3: AI Code Review ────────────────────────────────
        review_result = await self.review_pr_by_number(pr_number, abs_files,
                                                        pr_title=bug.get("title", ""),
                                                        pr_body=pr_body)

        self._review_count += 1
        self._history.append({
            "pr_number": pr_number,
            "bug_id": bug_id,
            "presubmit": "PASS",
            "review_verdict": review_result.get("verdict", "?") if review_result else "SKIP",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

        return {
            "pr": pr_result,
            "presubmit": report.to_dict(),
            "review": review_result,
            "blocked": False,
        }

    async def _file_review_bugs(self, pr_number: int, pr_title: str, review) -> list[str]:
        """File bugs for issues found during code review.

        Only files bugs for REQUEST_CHANGES verdicts or reviews with
        CRITICAL/WARNING comments. Returns list of bug descriptions.
        """
        bugs_filed = []

        if review.verdict != "REQUEST_CHANGES" and review.critical_count == 0:
            return bugs_filed

        try:
            from persistence.db import create_bug_dedup

            # File one bug per critical issue, or a summary bug for warnings
            if review.critical_count > 0:
                for comment in review.comments:
                    if comment.severity == "CRITICAL":
                        title = f"[PR #{pr_number}] {comment.category}: {comment.message[:80]}"
                        bug = create_bug_dedup(
                            title=title,
                            severity="HIGH",
                            source=f"pr_review:PR#{pr_number}",
                            description=(
                                f"PR #{pr_number}: {pr_title}\n"
                                f"File: {comment.file}:{comment.line}\n"
                                f"Category: {comment.category}\n"
                                f"Issue: {comment.message}"
                            ),
                        )
                        if bug:
                            bugs_filed.append(title[:60])
                            logger.info("review_bug_filed", pr=pr_number, title=title[:60])
            elif review.verdict == "REQUEST_CHANGES":
                # Summary bug for REQUEST_CHANGES without critical issues
                title = f"[PR #{pr_number}] Review: changes requested ({review.warning_count} warnings)"
                bug = create_bug_dedup(
                    title=title,
                    severity="MEDIUM",
                    source=f"pr_review:PR#{pr_number}",
                    description=(
                        f"PR #{pr_number}: {pr_title}\n"
                        f"Verdict: {review.verdict}\n"
                        f"Risk: {review.risk_score:.1f}\n"
                        f"Warnings: {review.warning_count}\n"
                        f"Summary: {review.summary}"
                    ),
                )
                if bug:
                    bugs_filed.append(title[:60])

        except Exception as e:
            logger.warning("review_bug_filing_failed", pr=pr_number, error=str(e))

        return bugs_filed

    async def review_pr_by_number(
        self,
        pr_number: int,
        file_paths: list[str] = None,
        pr_title: str = "",
        pr_body: str = "",
    ) -> Optional[dict]:
        """
        Run AI code review on an existing PR and post the review.

        Can be called standalone (for reviewing PRs from /review command)
        or as part of the presubmit_and_create_pr pipeline.
        """
        from agents.skills.pr_reviewer.code_review import code_reviewer
        from agents.skills.pr_reviewer.pr_tools import pr_tools

        # If no file paths given, fetch from GitHub
        if not file_paths:
            pr_files = await pr_tools.get_pr_files(pr_number)
            file_paths = [
                os.path.join(SRC_ROOT, f["filename"])
                for f in pr_files
                if f["status"] != "removed" and f["filename"].endswith(".py")
            ]

        if not pr_title:
            pr_data = await pr_tools.get_pr(pr_number)
            if pr_data:
                pr_title = pr_data.get("title", "")
                pr_body = pr_data.get("body", "")

        # Run AI review
        logger.info("ai_review_starting", pr=pr_number, files=len(file_paths))
        review = await code_reviewer.review_files(file_paths, pr_title, pr_body)

        # Post review on GitHub
        review_md = review.to_markdown()

        try:
            result = await pr_tools.post_review(
                pr_number=pr_number,
                body=review_md,
                event=review.verdict,
            )

            if result:
                logger.info(
                    "review_posted_to_github",
                    pr=pr_number,
                    verdict=review.verdict,
                    risk=review.risk_score,
                    comments=len(review.comments),
                )
        except Exception as e:
            # If we can't post a review (permissions), post as a comment instead
            logger.warning("review_post_as_comment", pr=pr_number, error=str(e))
            try:
                await pr_tools.post_comment(pr_number, review_md)
            except Exception:
                pass

        # Mark as reviewed in memory
        self._reviewed_prs.add(pr_number)

        # File bugs for issues found
        bugs_filed = await self._file_review_bugs(pr_number, pr_title, review)

        # Send consolidated Telegram notification
        try:
            from integrations.telegram_bot import send_alert
            icon = {"APPROVE": "✅", "REQUEST_CHANGES": "❌", "COMMENT": "💬"}.get(review.verdict, "📝")
            bugs_line = ""
            if bugs_filed:
                bugs_line = f"\n🐛 Bugs filed: {len(bugs_filed)}"
                for b in bugs_filed[:3]:
                    bugs_line += f"\n  • {b}"

            merge_status = ""
            if review.verdict == "APPROVE":
                merge_status = "\n🔀 Status: Queued for auto-merge"
            elif review.verdict == "REQUEST_CHANGES":
                merge_status = "\n🚫 Status: Blocked — changes needed"
            else:
                merge_status = "\n⏸ Status: Manual review recommended"

            await send_alert(
                f"🔍 *PR #{pr_number}* — `{pr_title[:50]}`\n"
                f"┣ {icon} Review: {review.verdict} (Risk: {review.risk_score:.1f}, "
                f"{review.critical_count} critical, {review.warning_count} warnings)"
                f"{bugs_line}"
                f"{merge_status}"
            )
        except Exception:
            pass

        return review.to_dict()

    async def review_all_open_prs(self) -> list[dict]:
        """Review all open PRs that haven't been reviewed yet.

        Uses two dedup layers:
          1. GitHub-level: pr_tools.list_unreviewed_prs() checks reviews+comments
          2. In-memory: self._reviewed_prs tracks PRs reviewed this process lifecycle
        """
        from agents.skills.pr_reviewer.pr_tools import pr_tools

        unreviewed = await pr_tools.list_unreviewed_prs()
        results = []

        for pr in unreviewed:
            # In-memory dedup — skip PRs already reviewed this process lifecycle
            if pr["number"] in self._reviewed_prs:
                logger.debug("pr_already_reviewed_in_memory", pr=pr["number"])
                continue

            try:
                result = await self.review_pr_by_number(pr["number"])
                results.append({
                    "pr": pr["number"],
                    "title": pr["title"],
                    "result": result,
                })
            except Exception as e:
                logger.error("review_failed", pr=pr["number"], error=str(e))

        return results

    async def review_loop(self, interval_minutes: int = 30):
        """Background loop: review unreviewed PRs periodically."""
        logger.info("pr_review_loop_started", interval=f"{interval_minutes}min")

        while True:
            try:
                results = await self.review_all_open_prs()
                if results:
                    logger.info("pr_review_cycle_done", reviewed=len(results))
                else:
                    logger.debug("pr_review_cycle_no_new_prs")
                await asyncio.sleep(interval_minutes * 60)
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error("pr_review_loop_error", error=str(e))
                await asyncio.sleep(60)

    def get_status(self) -> dict:
        return {
            "total_reviews": self._review_count,
            "recent": self._history[-10:],
        }


# Module-level singleton
review_pipeline = PRReviewPipeline()
