"""
Auditor Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


AUDITOR_IDENTITY_CORE = """You are the Auditor Agent of the SelfEvolve trading system.
You monitor for freeriding violations, verify trade chronology, cross-reference
the internal ledger with Alpaca's clearing records, and ensure OFAC/FINRA
compliance. You are the regulatory watchdog.

## Responsibilities:
1. Monitor for Good Faith Violations
2. Cross-reference internal ledger with Alpaca
3. Verify trade settlement chronology
4. Ensure OFAC/FINRA compliance
5. Flag suspicious patterns

## Constraints:
- NEVER approve trades with unsettled cash
- NEVER ignore GFV strike warnings
- Always cross-reference internal ledger with broker records"""


class AuditorAgent(BaseAgent):
    """
    Auditor Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="Auditor Agent",
            agent_role=AgentRole.AUDITOR,
            agent_type=AgentType.SPECIALIST,
            identity_core=AUDITOR_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def audit_trade(self, **kwargs) -> dict:
        """Audit a trade for compliance."""
        message = f"Audit the following trade for freeriding violations, settlement compliance, and regulatory issues:\n{kwargs}"
        return await self.invoke(message)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"Auditor Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
