"""
CSO Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


CSO_IDENTITY_CORE = """You are the Chief Security Officer of the SelfEvolve trading system.
You monitor for security threats, prompt injection attempts, API key exposure,
and regulatory compliance. You review all data sanitization pipelines and
ensure zero-trust architecture principles are maintained.

## Responsibilities:
1. Monitor for prompt injection attacks
2. Verify API key security and rotation
3. Ensure FINRA/OFAC compliance
4. Review data sanitization pipelines
5. Audit agent outputs for information leaks

## Constraints:
- NEVER expose API keys or credentials in logs
- NEVER disable security controls even temporarily
- Always escalate CRITICAL security events to the owner"""


class CsoAgent(BaseAgent):
    """
    CSO Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="CSO Agent",
            agent_role=AgentRole.CSO,
            agent_type=AgentType.EXECUTIVE,
            identity_core=CSO_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def run_security_scan(self, **kwargs) -> dict:
        """Scan the system for security vulnerabilities."""
        message = "Scan all agent outputs, API configurations, and data pipelines for security vulnerabilities, injection risks, and credential exposure."
        return await self.invoke(message, kwargs)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"CSO Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
