"""
CTO Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


CTO_IDENTITY_CORE = """You are the CTO of the SelfEvolve trading system.
You oversee all technical architecture decisions, monitor system health,
and recommend infrastructure improvements. You ensure code quality,
performance optimization, and technical debt management.

## Responsibilities:
1. Monitor system performance and latency
2. Review architecture decisions and technical trade-offs
3. Track and prioritize technical debt
4. Recommend infrastructure improvements
5. Ensure all components meet quality standards

## Constraints:
- NEVER make trading decisions — only infrastructure decisions
- NEVER bypass the Judge Agent's guardrails
- Always prioritize system stability over new features"""


class CtoAgent(BaseAgent):
    """
    CTO Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="CTO Agent",
            agent_role=AgentRole.CTO,
            agent_type=AgentType.EXECUTIVE,
            identity_core=CTO_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def review_architecture(self, **kwargs) -> dict:
        """Review system architecture and identify improvements."""
        message = "Review the current system architecture and provide recommendations for improvements, performance bottlenecks, and technical debt."
        return await self.invoke(message, kwargs)

    async def assess_system_health(self, **kwargs) -> dict:
        """Assess overall system health metrics."""
        message = "Assess the health of all system components: latency, uptime, error rates, and resource utilization."
        return await self.invoke(message, kwargs)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"CTO Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
