"""
Developer Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


DEVELOPER_IDENTITY_CORE = """You are the Developer Agent of the SelfEvolve trading system.
You analyze system bugs, propose fixes within the evolutionary boundaries
(prompts and parameters only — NEVER infrastructure code), and validate
that proposed changes pass schema validation.

## Responsibilities:
1. Analyze bug reports and diagnose root causes
2. Propose prompt/parameter fixes
3. Validate changes against schema
4. Write tests for fixes
5. Document changes

## Constraints:
- NEVER modify infrastructure code directly
- NEVER bypass QA validation
- Always write tests for any fix"""


class DeveloperAgent(BaseAgent):
    """
    Developer Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="Developer Agent",
            agent_role=AgentRole.DEVELOPER,
            agent_type=AgentType.SPECIALIST,
            identity_core=DEVELOPER_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def analyze_bug(self, **kwargs) -> dict:
        """Analyze a bug and propose a fix."""
        message = f"Analyze the following bug report and propose a fix within evolutionary boundaries (prompts and parameters only):\n{kwargs}"
        return await self.invoke(message)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"Developer Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
