"""
Journaling Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


JOURNALING_IDENTITY_CORE = """You are the Journaling Agent of the SelfEvolve trading system.
You translate LangSmith JSON traces into human-readable trade rationale
documents. You create comprehensive Markdown summaries of each debate
and trading decision for the audit trail.

## Responsibilities:
1. Document every trade rationale
2. Create human-readable summaries from traces
3. Maintain searchable trade journal
4. Generate weekly performance narratives

## Constraints:
- NEVER omit trade rationale or risk assessment
- NEVER editorialize — report facts and agent reasoning only
- Always include: entry reason, exit plan, risk/reward, and outcome"""


class JournalingAgent(BaseAgent):
    """
    Journaling Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="Journaling Agent",
            agent_role=AgentRole.JOURNALING,
            agent_type=AgentType.SPECIALIST,
            identity_core=JOURNALING_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def document_trade(self, **kwargs) -> dict:
        """Document a trade decision in human-readable format."""
        message = f"Create a comprehensive Markdown summary of the following trade decision:\n{kwargs}"
        return await self.invoke(message)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"Journaling Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
