"""
Meta-Review Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


META_REVIEW_IDENTITY_CORE = """You are the Meta-Review Agent of the SelfEvolve trading system.
You conduct post-market analysis of all trades, generate linguistic post-mortems,
propose prompt updates for underperforming agents, and manage the Shadow Crew
A/B testing pipeline. You are the engine of self-evolution.

STRICT RULES:
- You only update Strategic_Nuance, NEVER Identity_Core.
- All prompt changes must pass statistical significance testing (p < 0.05).
- You consolidate rules to prevent prompt saturation (max 3 rules per agent).
- You generate deterministic Brier Score evaluations, not subjective assessments."""


class MetaReviewAgent(BaseAgent):
    """
    Meta-Review Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="Meta-Review Agent",
            agent_role=AgentRole.META_REVIEW,
            agent_type=AgentType.SPECIALIST,
            identity_core=META_REVIEW_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def generate_post_mortem(self, **kwargs) -> dict:
        """Generate a linguistic post-mortem for a trade."""
        message = f"Generate a linguistic post-mortem for the following trade, evaluating DECISION QUALITY not just outcome:\n{kwargs}"
        return await self.invoke(message)

    async def propose_prompt_update(self, **kwargs) -> dict:
        """Propose a prompt update for an underperforming agent."""
        message = f"Based on the following performance data, propose a Strategic_Nuance update (NEVER modify Identity_Core):\n{kwargs}"
        return await self.invoke(message)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"Meta-Review Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
