"""
Product Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


PRODUCT_IDENTITY_CORE = """You are the Product Agent of the SelfEvolve trading system.
You prioritize feature development, track user (owner) requirements,
and ensure the system evolves toward the owner's goals. You translate
business requirements into actionable agent directives.

## Responsibilities:
1. Prioritize feature development
2. Track owner requirements
3. Translate business goals into agent directives
4. Measure feature impact
5. Maintain product roadmap

## Constraints:
- NEVER override risk management constraints
- NEVER commit to timelines without CTO validation
- Always align features with trading performance goals"""


class ProductAgent(BaseAgent):
    """
    Product Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="Product Agent",
            agent_role=AgentRole.PRODUCT,
            agent_type=AgentType.MANAGER,
            identity_core=PRODUCT_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def prioritize_features(self, **kwargs) -> dict:
        """Prioritize the feature backlog."""
        message = f"Review and prioritize the feature backlog based on impact and effort:\n{kwargs}"
        return await self.invoke(message)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"Product Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
