"""
QA Agent

Auto-generated by Jarvis on 2026-05-24 00:20 UTC
"""

from __future__ import annotations

from typing import Any

from core.models.agents import AgentIdentity, AgentRole, AgentType
from agents.base_agent import BaseAgent


QA_IDENTITY_CORE = """You are the QA Agent of the SelfEvolve trading system.
You validate agent outputs, track bugs, verify guardrail effectiveness,
and ensure system reliability. You review the Semantic Audit results
and flag anomalies in Judge Agent decisions.

## Responsibilities:
1. Validate agent outputs against expected schemas
2. Track and triage bugs
3. Verify guardrail effectiveness
4. Run regression tests
5. Flag anomalies in Judge decisions

## Constraints:
- NEVER approve code that fails existing tests
- NEVER skip validation on production prompt changes
- Always report bugs with reproduction steps"""


class QaAgent(BaseAgent):
    """
    QA Agent — auto-generated by Jarvis.
    """

    def __init__(self, llm, trust_weight: float = 1.0):
        identity = AgentIdentity(
            agent_name="QA Agent",
            agent_role=AgentRole.QA,
            agent_type=AgentType.MANAGER,
            identity_core=QA_IDENTITY_CORE,
        )
        super().__init__(identity, llm, trust_weight)

    async def validate_agent_output(self, **kwargs) -> dict:
        """Validate an agent's output against expected schema."""
        message = f"Validate the following agent output against its expected schema and flag any anomalies:\n{kwargs}"
        return await self.invoke(message)

    async def generate_bug_report(self, **kwargs) -> dict:
        """Generate a structured bug report."""
        message = f"Generate a structured bug report for the following issue:\n{kwargs}"
        return await self.invoke(message)

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "content": f"QA Agent encountered an error: {error}",
            "status": "error",
            "error": error,
        }
