"""
Strategy Agent Base Class

Foundation for all algorithmic trading strategy agents in the SelfEvolve system.
Each strategy agent is a self-contained trading bot with:
  - Deterministic signal generation (no LLM in the hot path)
  - Self-evolving parameters (adjusted via statistical testing)
  - Full trade journaling (every decision stored with context)
  - Shadow mode (paper trade new parameters before promoting)

The strategy agent does NOT decide how much capital it gets —
that's the Portfolio Manager's job. It operates within its allocation.
"""

from __future__ import annotations

import uuid
import math
from abc import abstractmethod
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

import structlog
from pydantic import BaseModel, Field, field_validator

from agents.base_agent import BaseAgent
from core.models.agents import AgentIdentity, AgentRole, AgentType

logger = structlog.get_logger(component="strategy_base")


# ════════════════════════════════════════════════════════════════════
# ENUMS
# ════════════════════════════════════════════════════════════════════

class SignalType(str, Enum):
    """Trading signal direction."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    SHORT = "SHORT"      # For future margin support
    COVER = "COVER"      # For future margin support


class StrategyMode(str, Enum):
    """Strategy execution mode."""
    LIVE = "LIVE"         # Real money
    PAPER = "PAPER"       # Paper trading
    SHADOW = "SHADOW"     # Shadow testing new parameters
    BACKTEST = "BACKTEST" # Historical backtesting


class MarketRegimeAffinity(str, Enum):
    """How well a strategy performs in a given regime."""
    STRONG = "STRONG"     # Strategy excels
    NEUTRAL = "NEUTRAL"   # Strategy is unaffected
    WEAK = "WEAK"         # Strategy underperforms
    DISABLED = "DISABLED" # Strategy should not trade


# ════════════════════════════════════════════════════════════════════
# PYDANTIC MODELS
# ════════════════════════════════════════════════════════════════════

class StrategyParameters(BaseModel):
    """
    Mutable parameter set for a strategy agent.
    
    These parameters evolve through statistical testing —
    a new parameter set is only promoted to production if it
    demonstrates statistically significant improvement (p < 0.05)
    over the current production parameters.
    """
    version: int = Field(default=1, ge=1, description="Parameter version number")
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="Strategy-specific parameters",
    )
    promoted_at: Optional[datetime] = Field(
        default=None,
        description="When these params were promoted to production",
    )
    parent_version: Optional[int] = Field(
        default=None,
        description="Version these params evolved from",
    )
    change_description: str = Field(
        default="Initial parameters",
        description="What changed in this version and why",
    )


class StrategySignal(BaseModel):
    """
    A trading signal generated by a strategy agent.
    
    This is the primary output of every strategy agent.
    Signals flow to the Portfolio Manager for capital allocation.
    """
    signal_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique signal identifier",
    )
    strategy_name: str = Field(..., description="Source strategy agent name")
    strategy_version: int = Field(default=1, description="Parameter version used")
    ticker: str = Field(..., description="Asset symbol")
    signal_type: SignalType = Field(..., description="BUY/SELL/HOLD")
    strength: float = Field(
        ..., ge=0.0, le=1.0,
        description="Signal strength (0 = weak, 1 = very strong)",
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0,
        description="Confidence in the signal (0 = uncertain, 1 = certain)",
    )
    entry_price: Optional[float] = Field(
        default=None, ge=0,
        description="Suggested entry price",
    )
    stop_loss_price: Optional[float] = Field(
        default=None, ge=0,
        description="Suggested stop loss price",
    )
    take_profit_price: Optional[float] = Field(
        default=None, ge=0,
        description="Suggested take profit price",
    )
    rationale: str = Field(
        default="",
        description="Brief explanation of why this signal was generated",
    )
    market_data_snapshot: dict = Field(
        default_factory=dict,
        description="Snapshot of market data at signal generation time (for post-mortem)",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    @field_validator("ticker")
    @classmethod
    def uppercase_ticker(cls, v: str) -> str:
        return v.upper().strip()

    @property
    def risk_reward_ratio(self) -> Optional[float]:
        """Calculate risk:reward ratio if SL and TP are set."""
        if (
            self.entry_price
            and self.stop_loss_price
            and self.take_profit_price
            and self.entry_price != self.stop_loss_price
        ):
            risk = abs(self.entry_price - self.stop_loss_price)
            reward = abs(self.take_profit_price - self.entry_price)
            return round(reward / risk, 2) if risk > 0 else None
        return None


class TradeRecord(BaseModel):
    """
    A completed trade record for the strategy journal.
    
    Every trade is stored with full context (market data at decision time)
    for post-mortem evaluation by the self-evolution engine.
    """
    trade_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
    )
    signal_id: str = Field(..., description="Original signal that triggered this trade")
    strategy_name: str = Field(..., description="Source strategy")
    strategy_version: int = Field(default=1, description="Parameter version used")
    ticker: str = Field(..., description="Asset traded")
    action: SignalType = Field(..., description="BUY or SELL")
    entry_price: float = Field(..., ge=0, description="Actual fill price")
    exit_price: Optional[float] = Field(default=None, ge=0, description="Exit fill price")
    quantity: float = Field(..., ge=0, description="Shares (fractional)")
    notional: float = Field(..., ge=0, description="Dollar amount")
    stop_loss_price: Optional[float] = Field(default=None)
    take_profit_price: Optional[float] = Field(default=None)
    pnl_usd: Optional[float] = Field(default=None, description="Realized P&L in USD")
    pnl_pct: Optional[float] = Field(default=None, description="Realized P&L as percentage")
    is_winner: Optional[bool] = Field(default=None, description="Was this trade profitable?")
    entry_time: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    exit_time: Optional[datetime] = Field(default=None)
    hold_duration_minutes: Optional[int] = Field(default=None)
    market_data_at_entry: dict = Field(
        default_factory=dict,
        description="Full market data snapshot at entry (for Brier score evaluation)",
    )
    market_data_at_exit: dict = Field(default_factory=dict)
    predicted_probability: Optional[float] = Field(
        default=None, ge=0.0, le=1.0,
        description="Agent's predicted probability of profit (for Brier scoring)",
    )
    mode: StrategyMode = Field(
        default=StrategyMode.PAPER,
        description="Was this a live, paper, or shadow trade?",
    )

    def close(
        self,
        exit_price: float,
        exit_time: Optional[datetime] = None,
        market_data: Optional[dict] = None,
    ) -> None:
        """Close the trade with exit data."""
        self.exit_price = exit_price
        self.exit_time = exit_time or datetime.now(timezone.utc)
        if market_data:
            self.market_data_at_exit = market_data
        # Calculate P&L
        if self.action == SignalType.BUY:
            self.pnl_usd = round((exit_price - self.entry_price) * self.quantity, 4)
            self.pnl_pct = round(
                ((exit_price - self.entry_price) / self.entry_price) * 100, 4
            ) if self.entry_price > 0 else 0.0
        elif self.action == SignalType.SELL:
            self.pnl_usd = round((self.entry_price - exit_price) * self.quantity, 4)
            self.pnl_pct = round(
                ((self.entry_price - exit_price) / self.entry_price) * 100, 4
            ) if self.entry_price > 0 else 0.0
        self.is_winner = (self.pnl_usd or 0) > 0
        if self.exit_time and self.entry_time:
            delta = self.exit_time - self.entry_time
            self.hold_duration_minutes = int(delta.total_seconds() / 60)


# ════════════════════════════════════════════════════════════════════
# STRATEGY AGENT BASE CLASS
# ════════════════════════════════════════════════════════════════════

class StrategyAgent(BaseAgent):
    """
    Abstract base class for all algorithmic strategy agents.
    
    Every strategy agent:
    1. Scans market data deterministically (no LLM in signal generation)
    2. Produces StrategySignal objects (BUY/SELL/HOLD)
    3. Tracks all trades in a journal for self-evolution
    4. Evolves its parameters through statistical testing
    5. Operates in LIVE, PAPER, or SHADOW mode
    
    The LLM is used ONLY for:
    - Post-mortem reflection on trade outcomes
    - Generating parameter evolution suggestions
    - Explaining performance changes to Jarvis
    
    All signal generation is DETERMINISTIC Python.
    """

    def __init__(
        self,
        identity: AgentIdentity,
        llm,
        trust_weight: float = 1.0,
        mode: StrategyMode = StrategyMode.PAPER,
    ):
        super().__init__(identity, llm, trust_weight)
        self.mode = mode
        self._parameters: StrategyParameters = StrategyParameters(
            params=self._default_parameters()
        )
        self._shadow_parameters: Optional[StrategyParameters] = None
        self._trade_journal: list[TradeRecord] = []
        self._active_trades: dict[str, TradeRecord] = {}  # ticker -> active trade
        self._allocated_capital: float = 0.0
        self._strategy_logger = structlog.get_logger(
            component=f"strategy.{self.strategy_name}"
        )

    # ── Abstract Methods (must be implemented by each strategy) ────

    @property
    @abstractmethod
    def strategy_name(self) -> str:
        """Unique name for this strategy (e.g., 'momentum', 'mean_reversion')."""
        ...

    @abstractmethod
    def _default_parameters(self) -> dict[str, Any]:
        """Return the default parameter set for this strategy."""
        ...

    @abstractmethod
    async def generate_signals(
        self,
        tickers: list[str],
        market_data: dict[str, Any],
    ) -> list[StrategySignal]:
        """
        Scan market data and generate trading signals.
        
        THIS MUST BE DETERMINISTIC — no LLM calls.
        
        Args:
            tickers: List of tickers to evaluate
            market_data: Pre-fetched market data keyed by ticker
            
        Returns:
            List of StrategySignal objects (only actionable signals)
        """
        ...

    @abstractmethod
    def get_regime_affinity(self) -> dict[str, MarketRegimeAffinity]:
        """
        Return how this strategy performs in each market regime.
        
        Returns:
            Dict mapping regime name to affinity level, e.g.:
            {"BULL": STRONG, "BEAR": WEAK, "SIDEWAYS": NEUTRAL, ...}
        """
        ...

    # ── Capital Management ─────────────────────────────────────────

    def set_allocation(self, capital: float) -> None:
        """Set the capital allocated to this strategy by the Portfolio Manager."""
        old = self._allocated_capital
        self._allocated_capital = max(0.0, capital)
        self._strategy_logger.info(
            "allocation_updated",
            strategy=self.strategy_name,
            old_allocation=old,
            new_allocation=self._allocated_capital,
        )

    @property
    def allocated_capital(self) -> float:
        return self._allocated_capital

    @property
    def available_capital(self) -> float:
        """Capital not currently deployed in active trades."""
        deployed = sum(
            t.notional for t in self._active_trades.values()
        )
        return max(0.0, self._allocated_capital - deployed)

    # ── Parameter Management ───────────────────────────────────────

    @property
    def parameters(self) -> StrategyParameters:
        return self._parameters

    @property
    def params(self) -> dict[str, Any]:
        """Shortcut to get current parameter values."""
        return self._parameters.params

    def get_param(self, key: str, default: Any = None) -> Any:
        """Get a specific parameter value."""
        return self._parameters.params.get(key, default)

    def propose_parameter_update(
        self,
        new_params: dict[str, Any],
        description: str,
    ) -> StrategyParameters:
        """
        Propose new parameters for shadow testing.
        
        Does NOT apply them to production — they go to shadow mode first.
        """
        self._shadow_parameters = StrategyParameters(
            version=self._parameters.version + 1,
            params={**self._parameters.params, **new_params},
            parent_version=self._parameters.version,
            change_description=description,
        )
        self._strategy_logger.info(
            "parameter_update_proposed",
            strategy=self.strategy_name,
            new_version=self._shadow_parameters.version,
            changes=new_params,
            description=description,
        )
        return self._shadow_parameters

    def promote_shadow_parameters(self) -> None:
        """Promote shadow parameters to production after statistical validation."""
        if self._shadow_parameters is None:
            raise ValueError("No shadow parameters to promote")
        
        old_version = self._parameters.version
        self._shadow_parameters.promoted_at = datetime.now(timezone.utc)
        self._parameters = self._shadow_parameters
        self._shadow_parameters = None
        
        self._strategy_logger.info(
            "parameters_promoted",
            strategy=self.strategy_name,
            old_version=old_version,
            new_version=self._parameters.version,
        )

    def rollback_parameters(self) -> None:
        """Discard shadow parameters."""
        if self._shadow_parameters:
            self._strategy_logger.info(
                "parameters_rolled_back",
                strategy=self.strategy_name,
                discarded_version=self._shadow_parameters.version,
            )
            self._shadow_parameters = None

    # ── Trade Journaling ───────────────────────────────────────────

    def record_entry(
        self,
        signal: StrategySignal,
        fill_price: float,
        quantity: float,
        market_data: Optional[dict] = None,
    ) -> TradeRecord:
        """Record a trade entry in the journal."""
        trade = TradeRecord(
            signal_id=signal.signal_id,
            strategy_name=self.strategy_name,
            strategy_version=self._parameters.version,
            ticker=signal.ticker,
            action=signal.signal_type,
            entry_price=fill_price,
            quantity=quantity,
            notional=round(fill_price * quantity, 2),
            stop_loss_price=signal.stop_loss_price,
            take_profit_price=signal.take_profit_price,
            predicted_probability=signal.confidence,
            market_data_at_entry=market_data or signal.market_data_snapshot,
            mode=self.mode,
        )
        self._active_trades[signal.ticker] = trade
        self._trade_journal.append(trade)
        
        self._strategy_logger.info(
            "trade_entered",
            strategy=self.strategy_name,
            ticker=signal.ticker,
            action=signal.signal_type.value,
            price=fill_price,
            quantity=quantity,
            mode=self.mode.value,
        )
        return trade

    def record_exit(
        self,
        ticker: str,
        exit_price: float,
        market_data: Optional[dict] = None,
    ) -> Optional[TradeRecord]:
        """Record a trade exit and calculate P&L."""
        trade = self._active_trades.pop(ticker, None)
        if trade is None:
            self._strategy_logger.warning(
                "exit_no_active_trade",
                strategy=self.strategy_name,
                ticker=ticker,
            )
            return None

        trade.close(exit_price, market_data=market_data)
        
        self._strategy_logger.info(
            "trade_exited",
            strategy=self.strategy_name,
            ticker=ticker,
            pnl_usd=trade.pnl_usd,
            pnl_pct=trade.pnl_pct,
            is_winner=trade.is_winner,
            hold_minutes=trade.hold_duration_minutes,
            mode=self.mode.value,
        )
        return trade

    def has_active_position(self, ticker: str) -> bool:
        """Check if there's an active trade for a ticker."""
        return ticker in self._active_trades

    # ── Performance Metrics ────────────────────────────────────────

    def get_performance(
        self,
        window_days: Optional[int] = None,
    ) -> dict[str, Any]:
        """
        Calculate comprehensive performance metrics.
        
        All calculations are deterministic Python — no LLM.
        """
        closed = [t for t in self._trade_journal if t.exit_price is not None]
        
        if window_days is not None:
            cutoff = datetime.now(timezone.utc).replace(
                hour=0, minute=0, second=0, microsecond=0
            )
            from datetime import timedelta
            cutoff -= timedelta(days=window_days)
            closed = [t for t in closed if t.entry_time >= cutoff]
        
        if not closed:
            return self._empty_performance()

        pnls = [t.pnl_pct or 0.0 for t in closed]
        pnl_usds = [t.pnl_usd or 0.0 for t in closed]
        wins = [p for p in pnls if p > 0]
        losses = [p for p in pnls if p <= 0]

        total_return = sum(pnls)
        avg_return = total_return / len(pnls)
        std_return = (
            math.sqrt(sum((p - avg_return) ** 2 for p in pnls) / max(1, len(pnls) - 1))
            if len(pnls) > 1
            else 0.0
        )

        # Sharpe ratio (annualized, assuming ~252 trading days)
        sharpe = (
            (avg_return / std_return) * math.sqrt(252)
            if std_return > 0
            else 0.0
        )

        # Max drawdown
        cumulative = 0.0
        peak = 0.0
        max_dd = 0.0
        for p in pnls:
            cumulative += p
            peak = max(peak, cumulative)
            dd = peak - cumulative
            max_dd = max(max_dd, dd)

        # Profit factor
        gross_profit = sum(p for p in pnl_usds if p > 0)
        gross_loss = abs(sum(p for p in pnl_usds if p < 0))
        profit_factor = (
            gross_profit / gross_loss if gross_loss > 0 else float("inf")
        )

        # Consecutive wins/losses
        max_consec_wins = 0
        max_consec_losses = 0
        current_streak = 0
        for p in pnls:
            if p > 0:
                if current_streak > 0:
                    current_streak += 1
                else:
                    current_streak = 1
                max_consec_wins = max(max_consec_wins, current_streak)
            else:
                if current_streak < 0:
                    current_streak -= 1
                else:
                    current_streak = -1
                max_consec_losses = max(max_consec_losses, abs(current_streak))

        return {
            "strategy": self.strategy_name,
            "version": self._parameters.version,
            "mode": self.mode.value,
            "total_trades": len(closed),
            "active_trades": len(self._active_trades),
            "win_rate": round(len(wins) / len(pnls) * 100, 1),
            "total_return_pct": round(total_return, 2),
            "total_pnl_usd": round(sum(pnl_usds), 2),
            "avg_return_pct": round(avg_return, 2),
            "avg_win_pct": round(sum(wins) / max(1, len(wins)), 2),
            "avg_loss_pct": round(sum(losses) / max(1, len(losses)), 2),
            "sharpe_ratio": round(sharpe, 2),
            "max_drawdown_pct": round(max_dd, 2),
            "profit_factor": round(profit_factor, 2),
            "max_consecutive_wins": max_consec_wins,
            "max_consecutive_losses": max_consec_losses,
            "allocated_capital": self._allocated_capital,
            "available_capital": self.available_capital,
        }

    def _empty_performance(self) -> dict[str, Any]:
        """Return empty performance metrics."""
        return {
            "strategy": self.strategy_name,
            "version": self._parameters.version,
            "mode": self.mode.value,
            "total_trades": 0,
            "active_trades": len(self._active_trades),
            "win_rate": 0.0,
            "total_return_pct": 0.0,
            "total_pnl_usd": 0.0,
            "avg_return_pct": 0.0,
            "avg_win_pct": 0.0,
            "avg_loss_pct": 0.0,
            "sharpe_ratio": 0.0,
            "max_drawdown_pct": 0.0,
            "profit_factor": 0.0,
            "max_consecutive_wins": 0,
            "max_consecutive_losses": 0,
            "allocated_capital": self._allocated_capital,
            "available_capital": self.available_capital,
        }

    # ── Brier Score Integration ────────────────────────────────────

    def get_brier_inputs(self) -> tuple[list[float], list[int]]:
        """
        Extract predictions and outcomes for Brier Score calculation.
        
        Returns:
            Tuple of (predicted_probabilities, actual_outcomes)
            where outcomes are 1 (profitable) or 0 (not profitable)
        """
        closed = [
            t for t in self._trade_journal
            if t.exit_price is not None and t.predicted_probability is not None
        ]
        predictions = [t.predicted_probability for t in closed]
        outcomes = [1 if (t.pnl_usd or 0) > 0 else 0 for t in closed]
        return predictions, outcomes

    # ── Self-Evolution Hook ────────────────────────────────────────

    async def reflect_on_performance(self) -> dict[str, Any]:
        """
        Use LLM to reflect on recent performance and suggest parameter changes.
        
        This is the ONLY place where the LLM is called during the
        self-evolution cycle. The reflection is structured to prevent
        hindsight bias.
        """
        performance = self.get_performance(window_days=7)
        recent_trades = [
            {
                "ticker": t.ticker,
                "action": t.action.value,
                "pnl_pct": t.pnl_pct,
                "is_winner": t.is_winner,
                "hold_minutes": t.hold_duration_minutes,
                "predicted_probability": t.predicted_probability,
            }
            for t in self._trade_journal[-10:]
            if t.exit_price is not None
        ]

        message = f"""Reflect on the {self.strategy_name} strategy's recent performance.

CURRENT PARAMETERS (v{self._parameters.version}):
{self._parameters.params}

PERFORMANCE (last 7 days):
{performance}

RECENT TRADES (last 10):
{recent_trades}

RULES:
1. Do NOT evaluate based on individual trade outcomes — evaluate the PATTERN.
2. Consider if parameters need adjustment based on the AGGREGATE performance.
3. Only suggest ONE parameter change (to avoid overfitting to noise).
4. If performance is acceptable, suggest NO changes.
5. Maximum response: 200 words.

Output your assessment as:
- Overall assessment (1-2 sentences)
- Suggested change (or "No change recommended")
- If change: which parameter, from what value, to what value, and why
"""
        return await self.invoke(message)

    # ── BaseAgent Required ─────────────────────────────────────────

    def _safe_default(self, error: str) -> dict[str, Any]:
        return {
            "strategy": self.strategy_name,
            "error": error,
            "signals": [],
            "status": "error",
        }

    # ── Utility ────────────────────────────────────────────────────

    @staticmethod
    def calculate_rsi(closes: list[float], period: int = 14) -> list[float]:
        """Calculate RSI for a price series."""
        if len(closes) < period + 1:
            return []
        
        deltas = [closes[i] - closes[i - 1] for i in range(1, len(closes))]
        gains = [max(0, d) for d in deltas[:period]]
        losses_raw = [abs(min(0, d)) for d in deltas[:period]]
        
        avg_gain = sum(gains) / period
        avg_loss = sum(losses_raw) / period
        
        rsi_values = []
        for i in range(period, len(deltas)):
            if avg_loss == 0:
                rsi_values.append(100.0)
            else:
                rs = avg_gain / avg_loss
                rsi_values.append(100 - (100 / (1 + rs)))
            
            delta = deltas[i]
            avg_gain = (avg_gain * (period - 1) + max(0, delta)) / period
            avg_loss = (avg_loss * (period - 1) + abs(min(0, delta))) / period
        
        return rsi_values

    @staticmethod
    def calculate_bollinger_bands(
        closes: list[float],
        period: int = 20,
        std_dev: float = 2.0,
    ) -> tuple[list[float], list[float], list[float]]:
        """
        Calculate Bollinger Bands.
        
        Returns:
            Tuple of (upper_band, middle_band, lower_band) lists
        """
        if len(closes) < period:
            return [], [], []
        
        upper = []
        middle = []
        lower = []
        
        for i in range(period - 1, len(closes)):
            window = closes[i - period + 1 : i + 1]
            sma = sum(window) / period
            std = math.sqrt(sum((x - sma) ** 2 for x in window) / period)
            
            upper.append(sma + std_dev * std)
            middle.append(sma)
            lower.append(sma - std_dev * std)
        
        return upper, middle, lower

    @staticmethod
    def calculate_atr(
        highs: list[float],
        lows: list[float],
        closes: list[float],
        period: int = 14,
    ) -> list[float]:
        """Calculate Average True Range series."""
        if len(highs) < period + 1:
            return []
        
        true_ranges = []
        for i in range(1, len(highs)):
            tr = max(
                highs[i] - lows[i],
                abs(highs[i] - closes[i - 1]),
                abs(lows[i] - closes[i - 1]),
            )
            true_ranges.append(tr)
        
        if len(true_ranges) < period:
            return []
        
        # Initial ATR is simple average
        atr_values = [sum(true_ranges[:period]) / period]
        
        # Wilder's smoothing
        for i in range(period, len(true_ranges)):
            atr = (atr_values[-1] * (period - 1) + true_ranges[i]) / period
            atr_values.append(atr)
        
        return atr_values

    @staticmethod
    def calculate_ema(values: list[float], period: int) -> list[float]:
        """Calculate Exponential Moving Average."""
        if len(values) < period:
            return []
        
        multiplier = 2 / (period + 1)
        ema_values = [sum(values[:period]) / period]
        
        for i in range(period, len(values)):
            ema = (values[i] - ema_values[-1]) * multiplier + ema_values[-1]
            ema_values.append(ema)
        
        return ema_values

    @staticmethod
    def calculate_vwap(
        highs: list[float],
        lows: list[float],
        closes: list[float],
        volumes: list[float],
    ) -> list[float]:
        """Calculate Volume Weighted Average Price."""
        if not highs or len(highs) != len(volumes):
            return []
        
        typical_prices = [
            (h + l + c) / 3 for h, l, c in zip(highs, lows, closes)
        ]
        
        cum_tp_vol = 0.0
        cum_vol = 0.0
        vwap_values = []
        
        for tp, vol in zip(typical_prices, volumes):
            cum_tp_vol += tp * vol
            cum_vol += vol
            vwap_values.append(cum_tp_vol / cum_vol if cum_vol > 0 else tp)
        
        return vwap_values
