"""
Audit, Bug Tracking, and Observability Models

Models for immutable audit trails, automated bug reports, evolution records,
system health events, and LLM cost tracking.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class AuditEventType(str, Enum):
    """Types of auditable events in the system."""
    TRADE_EXECUTED = "TRADE_EXECUTED"
    TRADE_REJECTED = "TRADE_REJECTED"
    TRADE_CANCELLED = "TRADE_CANCELLED"
    HITL_TRIGGERED = "HITL_TRIGGERED"
    HITL_APPROVED = "HITL_APPROVED"
    HITL_REJECTED = "HITL_REJECTED"
    HITL_TIMEOUT = "HITL_TIMEOUT"
    CIRCUIT_BREAKER_TRIP = "CIRCUIT_BREAKER_TRIP"
    CIRCUIT_BREAKER_RESET = "CIRCUIT_BREAKER_RESET"
    HCF_TRIGGERED = "HCF_TRIGGERED"
    EVOLUTION_EVENT = "EVOLUTION_EVENT"
    PROMPT_PROMOTED = "PROMPT_PROMOTED"
    PROMPT_ROLLED_BACK = "PROMPT_ROLLED_BACK"
    BUG_FILED = "BUG_FILED"
    BUG_RESOLVED = "BUG_RESOLVED"
    AGENT_SPAWNED = "AGENT_SPAWNED"
    AGENT_RETIRED = "AGENT_RETIRED"
    AGENT_EVOLVED = "AGENT_EVOLVED"
    GFV_INTENTIONAL = "GFV_INTENTIONAL"
    DRAWDOWN_ALERT = "DRAWDOWN_ALERT"
    LEDGER_DRIFT = "LEDGER_DRIFT"
    SYSTEM_STARTUP = "SYSTEM_STARTUP"
    SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN"


class BugSeverity(str, Enum):
    """Bug severity classification."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class BugStatus(str, Enum):
    """Bug lifecycle state."""
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    WONT_FIX = "WONT_FIX"


class HealthEventType(str, Enum):
    """System health event types."""
    HEARTBEAT = "HEARTBEAT"
    HEARTBEAT_STALE = "HEARTBEAT_STALE"
    CIRCUIT_BREAKER_TRIP = "CIRCUIT_BREAKER_TRIP"
    CIRCUIT_BREAKER_RESET = "CIRCUIT_BREAKER_RESET"
    DAEMON_CRASH = "DAEMON_CRASH"
    DAEMON_RECOVERY = "DAEMON_RECOVERY"
    HCF = "HCF"
    MEMORY_WARNING = "MEMORY_WARNING"
    API_LATENCY_SPIKE = "API_LATENCY_SPIKE"
    BUDGET_FREEZE = "BUDGET_FREEZE"


class AuditEvent(BaseModel):
    """
    Immutable audit event record.
    
    Every significant system action generates an audit event.
    These are stored in WORM-style storage and cannot be modified.
    """
    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique event identifier",
    )
    event_type: AuditEventType = Field(
        ..., description="Classification of the event"
    )
    agent_id: Optional[str] = Field(
        default=None, description="Agent that triggered the event"
    )
    trade_id: Optional[str] = Field(
        default=None, description="Associated trade ID if applicable"
    )
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured event data",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    model_config = {"frozen": True}  # Immutable after creation


class BugReport(BaseModel):
    """
    Automatically filed bug report.
    
    Generated by circuit breakers, hallucination catchers, GFV near-misses,
    and other system anomalies. Tracked and resolved by the QA Agent.
    """
    bug_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique bug identifier",
    )
    severity: BugSeverity = Field(
        ..., description="Bug severity level"
    )
    source_agent: Optional[str] = Field(
        default=None, description="Agent that discovered/caused the bug"
    )
    category: str = Field(
        default="UNKNOWN", description="Bug category (e.g., HALLUCINATION, GFV, CRASH)"
    )
    title: str = Field(..., min_length=1, description="Brief bug title")
    description: str = Field(
        ..., description="Detailed bug description"
    )
    stack_trace: Optional[str] = Field(
        default=None, description="Stack trace if applicable"
    )
    reproduction_steps: Optional[str] = Field(
        default=None, description="Steps to reproduce"
    )
    expected_behavior: Optional[str] = Field(
        default=None, description="What should have happened"
    )
    actual_behavior: Optional[str] = Field(
        default=None, description="What actually happened"
    )
    status: BugStatus = Field(
        default=BugStatus.OPEN, description="Current bug status"
    )
    assigned_to: Optional[str] = Field(
        default=None, description="Agent assigned to fix"
    )
    resolution: Optional[str] = Field(
        default=None, description="Resolution description"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    resolved_at: Optional[datetime] = None


class EvolutionRecord(BaseModel):
    """
    Record of a prompt/strategy evolution event.
    
    Tracks what changed, the statistical evidence, and whether
    the change was promoted to production or rolled back.
    """
    record_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique evolution record ID",
    )
    agent_id: str = Field(..., description="Agent that evolved")
    old_version: int = Field(..., description="Previous prompt version")
    new_version: int = Field(..., description="New prompt version")
    change_description: str = Field(
        ..., description="What was changed and why"
    )
    brier_before: float = Field(
        default=0.5, description="Brier score before evolution"
    )
    brier_after: float = Field(
        default=0.5, description="Brier score after evolution"
    )
    sharpe_before: Optional[float] = Field(
        default=None, description="Sharpe ratio before"
    )
    sharpe_after: Optional[float] = Field(
        default=None, description="Sharpe ratio after"
    )
    statistical_significance: float = Field(
        default=1.0, description="P-value of the improvement"
    )
    trade_count: int = Field(
        default=0, description="Number of trades in evaluation window"
    )
    promoted: bool = Field(
        default=False, description="Whether the change was promoted to production"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


class SystemHealthEvent(BaseModel):
    """System health monitoring event."""
    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
    )
    component: str = Field(
        ..., description="System component (e.g., 'overwatch', 'execution', 'redis')"
    )
    event_type: HealthEventType = Field(
        ..., description="Health event classification"
    )
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Event-specific data",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


class CostRecord(BaseModel):
    """
    LLM API cost record for a single task execution.
    
    Used by the CostTracker to calculate Net PnL (trading profit - API costs).
    """
    task_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
    )
    agent_role: str = Field(..., description="Role of the agent that made the call")
    model_used: str = Field(..., description="LLM model identifier")
    prompt_tokens: int = Field(default=0, ge=0, description="Input tokens")
    completion_tokens: int = Field(default=0, ge=0, description="Output tokens")
    total_cost_usd: float = Field(
        default=0.0, ge=0, description="Total cost in USD"
    )
    task_type: str = Field(
        default="unknown", description="Type of task (debate, judge, research, etc.)"
    )
    confidence_score: Optional[float] = Field(
        default=None, description="Confidence of the output"
    )
    escalated: bool = Field(
        default=False, description="Whether this was escalated from efficient to premium"
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
