"""
Strategy Domain Models

Pydantic models for multi-strategy trading signals, parameter versioning,
performance attribution, and portfolio allocation decisions.

These models enforce type safety across the entire strategy pipeline:
    Strategy Agent → Signal → Portfolio Manager → Allocation → Execution
"""

from __future__ import annotations

import uuid
import math
from datetime import datetime, timezone
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator, computed_field


# ════════════════════════════════════════════════════════════════════
# ENUMS
# ════════════════════════════════════════════════════════════════════

class StrategyType(str, Enum):
    """Supported trading strategy archetypes."""
    MOMENTUM = "MOMENTUM"
    MEAN_REVERSION = "MEAN_REVERSION"
    BREAKOUT = "BREAKOUT"
    PAIRS_TRADING = "PAIRS_TRADING"
    VWAP = "VWAP"


class SignalDirection(str, Enum):
    """Trade signal direction."""
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


class ExitType(str, Enum):
    """Reason for exiting a position."""
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT = "TAKE_PROFIT"
    TRAILING_STOP = "TRAILING_STOP"
    SIGNAL_EXIT = "SIGNAL_EXIT"
    TIME_EXIT = "TIME_EXIT"
    REGIME_CHANGE = "REGIME_CHANGE"
    MANUAL = "MANUAL"


class ParameterStatus(str, Enum):
    """Lifecycle state of a parameter version."""
    LIVE = "LIVE"
    SHADOW = "SHADOW"
    RETIRED = "RETIRED"
    CANDIDATE = "CANDIDATE"


class StrategyStatus(str, Enum):
    """Lifecycle state of a strategy agent."""
    ACTIVE = "ACTIVE"
    SHADOW = "SHADOW"
    PAUSED = "PAUSED"
    RETIRED = "RETIRED"


class MarketRegimeType(str, Enum):
    """Fine-grained market regime for strategy routing."""
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    MEAN_REVERTING = "MEAN_REVERTING"
    VOLATILE = "VOLATILE"
    BREAKOUT = "BREAKOUT"
    LOW_VOLATILITY = "LOW_VOLATILITY"


# ════════════════════════════════════════════════════════════════════
# SIGNALS
# ════════════════════════════════════════════════════════════════════

class Signal(BaseModel):
    """
    Trading signal generated by a strategy agent.

    This is the atomic unit of strategy output — a typed, validated
    instruction that flows to the Portfolio Manager for aggregation.
    """
    signal_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique signal identifier",
    )
    ticker: str = Field(..., description="Asset symbol")
    strategy_name: str = Field(..., description="Source strategy agent name")
    strategy_type: StrategyType = Field(..., description="Strategy archetype")
    direction: SignalDirection = Field(..., description="Trade direction")
    strength: float = Field(
        ..., ge=0.0, le=1.0,
        description="Signal strength (0 = weak, 1 = maximum conviction)",
    )
    entry_price: float = Field(..., gt=0, description="Recommended entry price")
    stop_loss: float = Field(..., gt=0, description="Stop loss price")
    take_profit: float = Field(..., gt=0, description="Take profit target")
    confidence: float = Field(
        ..., ge=0.0, le=1.0,
        description="Strategy confidence in this signal",
    )
    reasoning: str = Field(
        ..., max_length=500,
        description="Deterministic reasoning for the signal",
    )
    parameter_version: int = Field(
        default=1,
        description="Parameter version that generated this signal",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    @field_validator("ticker")
    @classmethod
    def uppercase_ticker(cls, v: str) -> str:
        return v.upper().strip()

    @computed_field
    @property
    def risk_reward_ratio(self) -> float:
        """Risk/reward ratio. Higher is better (target > 2.0)."""
        if self.direction == SignalDirection.LONG:
            risk = self.entry_price - self.stop_loss
            reward = self.take_profit - self.entry_price
        elif self.direction == SignalDirection.SHORT:
            risk = self.stop_loss - self.entry_price
            reward = self.entry_price - self.take_profit
        else:
            return 0.0
        if risk <= 0:
            return 0.0
        return round(reward / risk, 2)

    @computed_field
    @property
    def risk_pct(self) -> float:
        """Percentage risk from entry to stop loss."""
        if self.entry_price == 0:
            return 0.0
        if self.direction == SignalDirection.LONG:
            return round(abs(self.entry_price - self.stop_loss) / self.entry_price * 100, 2)
        elif self.direction == SignalDirection.SHORT:
            return round(abs(self.stop_loss - self.entry_price) / self.entry_price * 100, 2)
        return 0.0


class EntryDecision(BaseModel):
    """Strategy agent's entry decision for a specific ticker."""
    should_enter: bool = Field(..., description="Whether to enter the position")
    signal: Optional[Signal] = Field(
        default=None, description="Signal details if entering",
    )
    reasoning: str = Field(..., description="Explanation for the decision")
    data_snapshot: dict = Field(
        default_factory=dict,
        description="Market data available at decision time (for post-mortem)",
    )


class ExitDecision(BaseModel):
    """Strategy agent's exit decision for an open position."""
    should_exit: bool = Field(..., description="Whether to exit the position")
    exit_type: Optional[ExitType] = Field(
        default=None, description="Reason for exit",
    )
    exit_price: Optional[float] = Field(
        default=None, description="Recommended exit price",
    )
    reasoning: str = Field(..., description="Explanation for the decision")


# ════════════════════════════════════════════════════════════════════
# PARAMETER EVOLUTION
# ════════════════════════════════════════════════════════════════════

class ParameterVersion(BaseModel):
    """
    A versioned snapshot of strategy parameters.

    Every parameter change is logged with full context for
    audit trail and rollback capability.
    """
    version: int = Field(..., ge=1, description="Sequential version number")
    params: dict = Field(..., description="The parameter values")
    activated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    deactivated_at: Optional[datetime] = Field(
        default=None, description="When this version was replaced",
    )
    trade_count: int = Field(default=0, ge=0, description="Trades under this version")
    win_count: int = Field(default=0, ge=0, description="Winning trades")
    total_pnl: float = Field(default=0.0, description="Cumulative P&L")
    sharpe: float = Field(default=0.0, description="Sharpe ratio under this version")
    max_drawdown: float = Field(default=0.0, description="Max drawdown under this version")
    status: ParameterStatus = Field(
        default=ParameterStatus.LIVE,
        description="Lifecycle state",
    )
    change_reason: str = Field(
        default="", description="Why this version was created",
    )

    @computed_field
    @property
    def win_rate(self) -> float:
        """Win rate under this parameter version."""
        if self.trade_count == 0:
            return 0.0
        return round(self.win_count / self.trade_count, 4)

    @computed_field
    @property
    def avg_pnl_per_trade(self) -> float:
        """Average P&L per trade."""
        if self.trade_count == 0:
            return 0.0
        return round(self.total_pnl / self.trade_count, 4)


class ParameterEvolution(BaseModel):
    """
    A proposed parameter change with statistical justification.

    Only promoted to production when p < 0.05 vs current params.
    """
    strategy_name: str = Field(..., description="Source strategy")
    current_version: int = Field(..., description="Current parameter version")
    proposed_version: int = Field(..., description="Proposed version number")
    current_params: dict = Field(..., description="Current parameter values")
    proposed_params: dict = Field(..., description="Proposed parameter values")
    changes: dict = Field(
        ..., description="Params that changed: {name: {old, new, reason}}",
    )
    statistical_evidence: dict = Field(
        default_factory=dict,
        description="T-test results, p-value, confidence interval",
    )
    backtest_comparison: dict = Field(
        default_factory=dict,
        description="Current vs proposed backtest results",
    )
    recommendation: Literal["PROMOTE", "CONTINUE_TESTING", "REJECT"] = Field(
        default="CONTINUE_TESTING",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


# ════════════════════════════════════════════════════════════════════
# TRADE RECORDS
# ════════════════════════════════════════════════════════════════════

class TradeRecord(BaseModel):
    """
    Complete record of a strategy trade for performance attribution.

    Captures everything needed for post-mortem analysis and learning.
    """
    trade_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
    )
    strategy_name: str = Field(..., description="Strategy that generated the trade")
    strategy_type: StrategyType = Field(..., description="Strategy archetype")
    ticker: str = Field(..., description="Asset traded")
    direction: SignalDirection = Field(..., description="Trade direction")
    entry_price: float = Field(..., gt=0, description="Actual entry price")
    exit_price: Optional[float] = Field(default=None, description="Actual exit price")
    quantity: float = Field(..., gt=0, description="Shares traded")
    notional: float = Field(..., gt=0, description="Dollar amount")
    stop_loss: float = Field(..., gt=0, description="Stop loss at entry")
    take_profit: float = Field(..., gt=0, description="Take profit at entry")
    entry_time: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    exit_time: Optional[datetime] = Field(default=None)
    exit_type: Optional[ExitType] = Field(default=None)
    signal_strength: float = Field(default=0.0, ge=0.0, le=1.0)
    signal_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    parameter_version: int = Field(default=1)
    market_regime: Optional[MarketRegimeType] = Field(default=None)
    data_at_entry: dict = Field(
        default_factory=dict,
        description="Market data snapshot at entry for post-mortem replay",
    )
    data_at_exit: dict = Field(
        default_factory=dict,
        description="Market data snapshot at exit",
    )

    @field_validator("ticker")
    @classmethod
    def uppercase_ticker(cls, v: str) -> str:
        return v.upper().strip()

    @computed_field
    @property
    def pnl(self) -> float:
        """Realized P&L for closed trades."""
        if self.exit_price is None:
            return 0.0
        if self.direction == SignalDirection.LONG:
            return (self.exit_price - self.entry_price) * self.quantity
        elif self.direction == SignalDirection.SHORT:
            return (self.entry_price - self.exit_price) * self.quantity
        return 0.0

    @computed_field
    @property
    def pnl_pct(self) -> float:
        """Realized P&L as percentage."""
        if self.exit_price is None or self.entry_price == 0:
            return 0.0
        if self.direction == SignalDirection.LONG:
            return round((self.exit_price - self.entry_price) / self.entry_price * 100, 2)
        elif self.direction == SignalDirection.SHORT:
            return round((self.entry_price - self.exit_price) / self.entry_price * 100, 2)
        return 0.0

    @computed_field
    @property
    def is_winner(self) -> bool:
        """Whether this trade was profitable."""
        return self.pnl > 0

    @computed_field
    @property
    def hold_duration_hours(self) -> float:
        """How long the position was held."""
        if self.exit_time is None:
            return 0.0
        delta = self.exit_time - self.entry_time
        return round(delta.total_seconds() / 3600, 2)


# ════════════════════════════════════════════════════════════════════
# STRATEGY PERFORMANCE
# ════════════════════════════════════════════════════════════════════

class StrategyPerformance(BaseModel):
    """
    Aggregated performance metrics for a single strategy.

    Calculated deterministically from TradeRecords — never by LLM.
    """
    strategy_name: str = Field(..., description="Strategy identifier")
    strategy_type: StrategyType = Field(..., description="Strategy archetype")
    status: StrategyStatus = Field(
        default=StrategyStatus.ACTIVE,
    )
    total_trades: int = Field(default=0, ge=0)
    winning_trades: int = Field(default=0, ge=0)
    losing_trades: int = Field(default=0, ge=0)
    total_pnl: float = Field(default=0.0, description="Cumulative P&L ($)")
    total_pnl_pct: float = Field(default=0.0, description="Cumulative P&L (%)")
    sharpe_ratio: float = Field(default=0.0, description="Annualized Sharpe")
    sortino_ratio: float = Field(default=0.0, description="Annualized Sortino")
    max_drawdown_pct: float = Field(default=0.0, description="Maximum drawdown (%)")
    profit_factor: float = Field(default=0.0, description="Gross profit / gross loss")
    avg_win_pct: float = Field(default=0.0, description="Average winning trade (%)")
    avg_loss_pct: float = Field(default=0.0, description="Average losing trade (%)")
    avg_hold_period_hours: float = Field(default=0.0)
    current_params_version: int = Field(default=1)
    allocation_pct: float = Field(
        default=0.0, ge=0.0, le=100.0,
        description="Current portfolio allocation (%)",
    )
    brier_score: float = Field(
        default=0.5, ge=0.0, le=1.0,
        description="Prediction calibration (lower = better)",
    )
    consecutive_losses: int = Field(default=0, ge=0)
    last_trade_time: Optional[datetime] = Field(default=None)
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    @computed_field
    @property
    def win_rate(self) -> float:
        """Win rate as fraction."""
        if self.total_trades == 0:
            return 0.0
        return round(self.winning_trades / self.total_trades, 4)

    @computed_field
    @property
    def expectancy(self) -> float:
        """Expected value per trade = (win_rate × avg_win) - (loss_rate × avg_loss)."""
        wr = self.win_rate
        lr = 1.0 - wr
        return round(wr * self.avg_win_pct - lr * abs(self.avg_loss_pct), 4)

    @computed_field
    @property
    def should_pause(self) -> bool:
        """Automatic pause trigger: 5+ consecutive losses or drawdown > 15%."""
        return self.consecutive_losses >= 5 or self.max_drawdown_pct > 15.0

    @staticmethod
    def compute_from_trades(
        strategy_name: str,
        strategy_type: StrategyType,
        trades: list[TradeRecord],
        allocation_pct: float = 0.0,
    ) -> "StrategyPerformance":
        """
        Compute performance metrics from a list of closed trades.

        All math is deterministic Python — no LLM involvement.
        """
        closed = [t for t in trades if t.exit_price is not None]
        if not closed:
            return StrategyPerformance(
                strategy_name=strategy_name,
                strategy_type=strategy_type,
                allocation_pct=allocation_pct,
            )

        pnls = [t.pnl_pct for t in closed]
        wins = [p for p in pnls if p > 0]
        losses = [p for p in pnls if p <= 0]

        total_pnl = sum(t.pnl for t in closed)
        avg_win = sum(wins) / len(wins) if wins else 0.0
        avg_loss = sum(losses) / len(losses) if losses else 0.0

        # Sharpe ratio (annualized, assuming ~252 trading days)
        if len(pnls) > 1:
            mean_ret = sum(pnls) / len(pnls)
            std_ret = math.sqrt(
                sum((p - mean_ret) ** 2 for p in pnls) / (len(pnls) - 1)
            )
            sharpe = (mean_ret / std_ret * math.sqrt(252)) if std_ret > 0 else 0.0

            # Sortino (only downside deviation)
            downside = [p for p in pnls if p < 0]
            if downside:
                down_std = math.sqrt(sum(p ** 2 for p in downside) / len(downside))
                sortino = (mean_ret / down_std * math.sqrt(252)) if down_std > 0 else 0.0
            else:
                sortino = sharpe * 1.5  # All wins = great sortino
        else:
            sharpe = 0.0
            sortino = 0.0

        # Max drawdown
        cumulative = 0.0
        peak = 0.0
        max_dd = 0.0
        for p in pnls:
            cumulative += p
            peak = max(peak, cumulative)
            dd = peak - cumulative
            max_dd = max(max_dd, dd)

        # Profit factor
        gross_profit = sum(wins) if wins else 0.0
        gross_loss = abs(sum(losses)) if losses else 1.0  # avoid /0
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else gross_profit

        # Consecutive losses (from end)
        consec = 0
        for p in reversed(pnls):
            if p <= 0:
                consec += 1
            else:
                break

        # Average hold period
        hold_hours = [t.hold_duration_hours for t in closed if t.hold_duration_hours > 0]
        avg_hold = sum(hold_hours) / len(hold_hours) if hold_hours else 0.0

        return StrategyPerformance(
            strategy_name=strategy_name,
            strategy_type=strategy_type,
            total_trades=len(closed),
            winning_trades=len(wins),
            losing_trades=len(losses),
            total_pnl=round(total_pnl, 2),
            total_pnl_pct=round(sum(pnls), 2),
            sharpe_ratio=round(sharpe, 2),
            sortino_ratio=round(sortino, 2),
            max_drawdown_pct=round(max_dd, 2),
            profit_factor=round(profit_factor, 2),
            avg_win_pct=round(avg_win, 2),
            avg_loss_pct=round(avg_loss, 2),
            avg_hold_period_hours=round(avg_hold, 2),
            allocation_pct=allocation_pct,
            consecutive_losses=consec,
            last_trade_time=closed[-1].exit_time if closed else None,
        )


# ════════════════════════════════════════════════════════════════════
# PORTFOLIO ALLOCATION
# ════════════════════════════════════════════════════════════════════

class AllocationDecision(BaseModel):
    """
    Portfolio Manager's allocation decision across all strategies.

    Determined by performance, regime, and risk constraints.
    """
    strategy_allocations: dict[str, float] = Field(
        ..., description="strategy_name → % of portfolio (must sum to <= 100)",
    )
    cash_reserve_pct: float = Field(
        default=10.0, ge=0.0, le=100.0,
        description="Cash held in reserve",
    )
    regime: MarketRegimeType = Field(
        ..., description="Current market regime influencing allocation",
    )
    reasoning: str = Field(
        ..., description="Explanation of allocation logic",
    )
    total_portfolio_value: float = Field(
        default=0.0, description="Total portfolio value at decision time",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    @computed_field
    @property
    def total_allocated_pct(self) -> float:
        """Total % allocated to strategies."""
        return round(sum(self.strategy_allocations.values()), 2)

    @field_validator("strategy_allocations")
    @classmethod
    def validate_allocations(cls, v: dict[str, float]) -> dict[str, float]:
        """Ensure no single strategy gets > 40% and total <= 100%."""
        total = sum(v.values())
        if total > 100.0:
            raise ValueError(
                f"Total allocation {total}% exceeds 100%. "
                "Reduce strategy weights."
            )
        for name, pct in v.items():
            if pct < 0:
                raise ValueError(f"Strategy '{name}' has negative allocation: {pct}%")
            if pct > 40:
                raise ValueError(
                    f"Strategy '{name}' allocation {pct}% exceeds 40% max. "
                    "Diversification required."
                )
        return v


class StrategyCorrelation(BaseModel):
    """Pairwise correlation between two strategies' returns."""
    strategy_a: str
    strategy_b: str
    correlation: float = Field(
        ..., ge=-1.0, le=1.0,
        description="Pearson correlation of daily returns",
    )
    period_days: int = Field(
        default=30, description="Lookback period for calculation",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


class PortfolioSnapshot(BaseModel):
    """
    Point-in-time snapshot of the multi-strategy portfolio.

    Used for performance attribution — "which strategy made the money?"
    """
    total_equity: float = Field(default=0.0)
    strategy_pnl: dict[str, float] = Field(
        default_factory=dict,
        description="P&L per strategy",
    )
    strategy_allocations: dict[str, float] = Field(
        default_factory=dict,
        description="Current allocation per strategy",
    )
    daily_pnl: float = Field(default=0.0)
    weekly_pnl: float = Field(default=0.0)
    monthly_pnl: float = Field(default=0.0)
    active_strategies: int = Field(default=0)
    active_positions: int = Field(default=0)
    regime: Optional[MarketRegimeType] = Field(default=None)
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
